"""Criação da hierarquia Porto Seguro e Ponto de Luz

Revision ID: 69edad102fe2
Revises: 
Create Date: 2026-04-21 01:02:41.216921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69edad102fe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('porto_seguro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('prazo', sa.DateTime(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto_de_luz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('prazo', sa.DateTime(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('porto_seguro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['porto_seguro_id'], ['porto_seguro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. MUDANÇA ROBUSTA: Migração de Dados
    # Vamos pegar cada meta antiga e transformá-la em um Porto Seguro
    # Para isso, usamos SQL puro via comando op.execute
    op.execute('''
        INSERT INTO porto_seguro (titulo, user_id, data_criacao, concluido)
        SELECT texto, user_id, CURRENT_TIMESTAMP, 0 FROM meta
    ''')
    
    op.drop_table('meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.VARCHAR(length=200), nullable=False),
    sa.Column('concluida', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ponto_de_luz')
    op.drop_table('porto_seguro')
    # ### end Alembic commands ###
